In [1]:
import pandas as pd

In [3]:
import os

print(os.getcwd())

C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data

In [4]:
os.listdir()

['.ipynb_checkpoints', 'globalterrorismdb_0718dist.csv', 'Untitled.ipynb']

In [6]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles in current folder:")
print(os.listdir())

Current folder:
C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data

Files in current folder:
['.ipynb_checkpoints', 'globalterrorismdb_0718dist.csv', 'Untitled.ipynb']

In [7]:
import pandas as pd

gtd = pd.read_csv(
    "globalterrorismdb_0718dist.csv",
    encoding="latin1",
    low_memory=False
)

print("Dataset loaded successfully!")
print("Rows:", gtd.shape[0])
print("Columns:", gtd.shape[1])

Dataset loaded successfully!
Rows: 171056
Columns: 135

In [8]:
gtd.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0.0,0.0,0.0,0.0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0.0,1.0,1.0,1.0,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN

In [9]:
gtd.columns.tolist()

['eventid',
 'iyear',
 'imonth',
 'iday',
 'approxdate',
 'extended',
 'resolution',
 'country',
 'country_txt',
 'region',
 'region_txt',
 'provstate',
 'city',
 'latitude',
 'longitude',
 'specificity',
 'vicinity',
 'location',
 'summary',
 'crit1',
 'crit2',
 'crit3',
 'doubtterr',
 'alternative',
 'alternative_txt',
 'multiple',
 'success',
 'suicide',
 'attacktype1',
 'attacktype1_txt',
 'attacktype2',
 'attacktype2_txt',
 'attacktype3',
 'attacktype3_txt',
 'targtype1',
 'targtype1_txt',
 'targsubtype1',
 'targsubtype1_txt',
 'corp1',
 'target1',
 'natlty1',
 'natlty1_txt',
 'targtype2',
 'targtype2_txt',
 'targsubtype2',
 'targsubtype2_txt',
 'corp2',
 'target2',
 'natlty2',
 'natlty2_txt',
 'targtype3',
 'targtype3_txt',
 'targsubtype3',
 'targsubtype3_txt',
 'corp3',
 'target3',
 'natlty3',
 'natlty3_txt',
 'gname',
 'gsubname',
 'gname2',
 'gsubname2',
 'gname3',
 'gsubname3',
 'motive',
 'guncertain1',
 'guncertain2',
 'guncertain3',
 'individual',
 'nperps',
 'nperpcap',
 'claimed',
 'claimmode',
 'claimmode_txt',
 'claim2',
 'claimmode2',
 'claimmode2_txt',
 'claim3',
 'claimmode3',
 'claimmode3_txt',
 'compclaim',
 'weaptype1',
 'weaptype1_txt',
 'weapsubtype1',
 'weapsubtype1_txt',
 'weaptype2',
 'weaptype2_txt',
 'weapsubtype2',
 'weapsubtype2_txt',
 'weaptype3',
 'weaptype3_txt',
 'weapsubtype3',
 'weapsubtype3_txt',
 'weaptype4',
 'weaptype4_txt',
 'weapsubtype4',
 'weapsubtype4_txt',
 'weapdetail',
 'nkill',
 'nkillus',
 'nkillter',
 'nwound',
 'nwoundus',
 'nwoundte',
 'property',
 'propextent',
 'propextent_txt',
 'propvalue',
 'propcomment',
 'ishostkid',
 'nhostkid',
 'nhostkidus',
 'nhours',
 'ndays',
 'divert',
 'kidhijcountry',
 'ransom',
 'ransomamt',
 'ransomamtus',
 'ransompaid',
 'ransompaidus',
 'ransomnote',
 'hostkidoutcome',
 'hostkidoutcome_txt',
 'nreleased',
 'addnotes',
 'scite1',
 'scite2',
 'scite3',
 'dbsource',
 'INT_LOG',
 'INT_IDEO',
 'INT_MISC',
 'INT_ANY',
 'related']

In [10]:
gtd.info()

<class 'pandas.DataFrame'>
RangeIndex: 171056 entries, 0 to 171055
Columns: 135 entries, eventid to related
dtypes: float64(60), int64(17), str(58)
memory usage: 285.0 MB

In [11]:
missing_summary = pd.DataFrame({
    "Missing_Count": gtd.isnull().sum(),
    "Missing_Percentage": gtd.isnull().mean() * 100
}).sort_values(
    "Missing_Percentage",
    ascending=False
)

missing_summary.head(20)

                  Missing_Count  Missing_Percentage
gsubname3                171042           99.991816
weapsubtype4             170986           99.959078
weapsubtype4_txt         170986           99.959078
weaptype4_txt            170983           99.957324
weaptype4                170983           99.957324
claimmode3               170935           99.929263
claimmode3_txt           170935           99.929263
gsubname2                170908           99.913479
claim3                   170788           99.843326
guncertain3              170786           99.842157
gname3                   170782           99.839819
divert                   170742           99.816434
attacktype3              170673           99.776097
attacktype3_txt          170673           99.776097
ransomnote               170580           99.721729
ransompaidus             170563           99.711790
ransomamtus              170552           99.705360
claimmode2_txt           170514           99.683145
claimmode2               170514           99.683145
ransompaid               170341           99.582008

In [12]:
print("Duplicate Rows:", gtd.duplicated().sum())
print("Duplicate Event IDs:", gtd["eventid"].duplicated().sum())
print("Unique Event IDs:", gtd["eventid"].nunique())

Duplicate Rows: 0
Duplicate Event IDs: 0
Unique Event IDs: 171056

In [13]:
print("Minimum Year:", gtd["iyear"].min())
print("Maximum Year:", gtd["iyear"].max())

Minimum Year: 1970
Maximum Year: 2017

In [14]:
print("Duplicate Rows:", gtd.duplicated().sum())
print("Duplicate Event IDs:", gtd["eventid"].duplicated().sum())
print("Unique Event IDs:", gtd["eventid"].nunique())

Duplicate Rows: 0
Duplicate Event IDs: 0
Unique Event IDs: 171056

In [16]:
important_columns = [
    "eventid",
    "iyear",
    "imonth",
    "iday",
    "country_txt",
    "region_txt",
    "city",
    "latitude",
    "longitude",
    "attacktype1_txt",
    "targtype1_txt",
    "weaptype1_txt",
    "gname",
    "nkill",
    "nwound",
    "motive"
]

for col in important_columns:
    print(col, "→", col in gtd.columns)

eventid → True
iyear → True
imonth → True
iday → True
country_txt → True
region_txt → True
city → True
latitude → True
longitude → True
attacktype1_txt → True
targtype1_txt → True
weaptype1_txt → True
gname → True
nkill → True
nwound → True
motive → True

In [17]:
gtd[["nkill", "nwound"]].isnull().sum()

nkill      9711
nwound    15372
dtype: int64

In [2]:
import pandas as pd

gtd = pd.read_csv(
    "globalterrorismdb_0718dist.csv",
    encoding="latin1",
    low_memory=False
)

print("Dataset loaded successfully!")
print("Rows:", gtd.shape[0])
print("Columns:", gtd.shape[1])

Dataset loaded successfully!
Rows: 171056
Columns: 135

In [3]:
print(gtd.columns.tolist())

['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended', 'resolution', 'country', 'country_txt', 'region', 'region_txt', 'provstate', 'city', 'latitude', 'longitude', 'specificity', 'vicinity', 'location', 'summary', 'crit1', 'crit2', 'crit3', 'doubtterr', 'alternative', 'alternative_txt', 'multiple', 'success', 'suicide', 'attacktype1', 'attacktype1_txt', 'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt', 'targtype1', 'targtype1_txt', 'targsubtype1', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1', 'natlty1_txt', 'targtype2', 'targtype2_txt', 'targsubtype2', 'targsubtype2_txt', 'corp2', 'target2', 'natlty2', 'natlty2_txt', 'targtype3', 'targtype3_txt', 'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3', 'natlty3', 'natlty3_txt', 'gname', 'gsubname', 'gname2', 'gsubname2', 'gname3', 'gsubname3', 'motive', 'guncertain1', 'guncertain2', 'guncertain3', 'individual', 'nperps', 'nperpcap', 'claimed', 'claimmode', 'claimmode_txt', 'claim2', 'claimmode2', 'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt', 'compclaim', 'weaptype1', 'weaptype1_txt', 'weapsubtype1', 'weapsubtype1_txt', 'weaptype2', 'weaptype2_txt', 'weapsubtype2', 'weapsubtype2_txt', 'weaptype3', 'weaptype3_txt', 'weapsubtype3', 'weapsubtype3_txt', 'weaptype4', 'weaptype4_txt', 'weapsubtype4', 'weapsubtype4_txt', 'weapdetail', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte', 'property', 'propextent', 'propextent_txt', 'propvalue', 'propcomment', 'ishostkid', 'nhostkid', 'nhostkidus', 'nhours', 'ndays', 'divert', 'kidhijcountry', 'ransom', 'ransomamt', 'ransomamtus', 'ransompaid', 'ransompaidus', 'ransomnote', 'hostkidoutcome', 'hostkidoutcome_txt', 'nreleased', 'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related']

In [4]:
column_definitions = ",\n".join(
    f'    "{col}" TEXT'
    for col in gtd.columns
)

create_table_sql = f"""
CREATE TABLE raw_gtd_events (
{column_definitions}
);
"""

print(create_table_sql)

CREATE TABLE raw_gtd_events (
    "eventid" TEXT,
    "iyear" TEXT,
    "imonth" TEXT,
    "iday" TEXT,
    "approxdate" TEXT,
    "extended" TEXT,
    "resolution" TEXT,
    "country" TEXT,
    "country_txt" TEXT,
    "region" TEXT,
    "region_txt" TEXT,
    "provstate" TEXT,
    "city" TEXT,
    "latitude" TEXT,
    "longitude" TEXT,
    "specificity" TEXT,
    "vicinity" TEXT,
    "location" TEXT,
    "summary" TEXT,
    "crit1" TEXT,
    "crit2" TEXT,
    "crit3" TEXT,
    "doubtterr" TEXT,
    "alternative" TEXT,
    "alternative_txt" TEXT,
    "multiple" TEXT,
    "success" TEXT,
    "suicide" TEXT,
    "attacktype1" TEXT,
    "attacktype1_txt" TEXT,
    "attacktype2" TEXT,
    "attacktype2_txt" TEXT,
    "attacktype3" TEXT,
    "attacktype3_txt" TEXT,
    "targtype1" TEXT,
    "targtype1_txt" TEXT,
    "targsubtype1" TEXT,
    "targsubtype1_txt" TEXT,
    "corp1" TEXT,
    "target1" TEXT,
    "natlty1" TEXT,
    "natlty1_txt" TEXT,
    "targtype2" TEXT,
    "targtype2_txt" TEXT,
    "targsubtype2" TEXT,
    "targsubtype2_txt" TEXT,
    "corp2" TEXT,
    "target2" TEXT,
    "natlty2" TEXT,
    "natlty2_txt" TEXT,
    "targtype3" TEXT,
    "targtype3_txt" TEXT,
    "targsubtype3" TEXT,
    "targsubtype3_txt" TEXT,
    "corp3" TEXT,
    "target3" TEXT,
    "natlty3" TEXT,
    "natlty3_txt" TEXT,
    "gname" TEXT,
    "gsubname" TEXT,
    "gname2" TEXT,
    "gsubname2" TEXT,
    "gname3" TEXT,
    "gsubname3" TEXT,
    "motive" TEXT,
    "guncertain1" TEXT,
    "guncertain2" TEXT,
    "guncertain3" TEXT,
    "individual" TEXT,
    "nperps" TEXT,
    "nperpcap" TEXT,
    "claimed" TEXT,
    "claimmode" TEXT,
    "claimmode_txt" TEXT,
    "claim2" TEXT,
    "claimmode2" TEXT,
    "claimmode2_txt" TEXT,
    "claim3" TEXT,
    "claimmode3" TEXT,
    "claimmode3_txt" TEXT,
    "compclaim" TEXT,
    "weaptype1" TEXT,
    "weaptype1_txt" TEXT,
    "weapsubtype1" TEXT,
    "weapsubtype1_txt" TEXT,
    "weaptype2" TEXT,
    "weaptype2_txt" TEXT,
    "weapsubtype2" TEXT,
    "weapsubtype2_txt" TEXT,
    "weaptype3" TEXT,
    "weaptype3_txt" TEXT,
    "weapsubtype3" TEXT,
    "weapsubtype3_txt" TEXT,
    "weaptype4" TEXT,
    "weaptype4_txt" TEXT,
    "weapsubtype4" TEXT,
    "weapsubtype4_txt" TEXT,
    "weapdetail" TEXT,
    "nkill" TEXT,
    "nkillus" TEXT,
    "nkillter" TEXT,
    "nwound" TEXT,
    "nwoundus" TEXT,
    "nwoundte" TEXT,
    "property" TEXT,
    "propextent" TEXT,
    "propextent_txt" TEXT,
    "propvalue" TEXT,
    "propcomment" TEXT,
    "ishostkid" TEXT,
    "nhostkid" TEXT,
    "nhostkidus" TEXT,
    "nhours" TEXT,
    "ndays" TEXT,
    "divert" TEXT,
    "kidhijcountry" TEXT,
    "ransom" TEXT,
    "ransomamt" TEXT,
    "ransomamtus" TEXT,
    "ransompaid" TEXT,
    "ransompaidus" TEXT,
    "ransomnote" TEXT,
    "hostkidoutcome" TEXT,
    "hostkidoutcome_txt" TEXT,
    "nreleased" TEXT,
    "addnotes" TEXT,
    "scite1" TEXT,
    "scite2" TEXT,
    "scite3" TEXT,
    "dbsource" TEXT,
    "INT_LOG" TEXT,
    "INT_IDEO" TEXT,
    "INT_MISC" TEXT,
    "INT_ANY" TEXT,
    "related" TEXT
);

In [5]:
column_definitions = ",\n".join(
    f'    "{col}" TEXT'
    for col in gtd.columns
)

create_table_sql = f"""CREATE TABLE raw_gtd_events (
{column_definitions}
);"""

print("SQL generated successfully!")
print("Number of columns:", len(gtd.columns))

SQL generated successfully!
Number of columns: 135

In [6]:
with open("create_raw_gtd_table.sql", "w", encoding="utf-8") as f:
    f.write(create_table_sql)

print("SQL file created successfully!")

SQL file created successfully!

In [1]:
import os

print(os.path.abspath("globalterrorismdb_0718dist.csv"))

C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\globalterrorismdb_0718dist.csv

In [2]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="gtd_db",
    user="postgres",
    password="তোমার PostgreSQL password"
)

cur = conn.cursor()

csv_path = r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\globalterrorismdb_0718dist.csv"

with open(csv_path, "r", encoding="latin1") as f:
    cur.copy_expert(
        """
        COPY raw_gtd_events
        FROM STDIN
        WITH (
            FORMAT CSV,
            HEADER TRUE,
            DELIMITER ',',
            QUOTE '"',
            ESCAPE '"'
        )
        """,
        f
    )

conn.commit()

cur.close()
conn.close()

print("CSV imported successfully!")

ModuleNotFoundError: No module named 'psycopg2'

In [2]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.9 MB 3.4 MB/s eta 0:00:01
   ---------- ----------------------------- 0.8/2.9 MB 1.4 MB/s eta 0:00:02
   -------------- ------------------------- 1.0/2.9 MB 1.2 MB/s eta 0:00:02
   --------------------- ------------------ 1.6/2.9 MB 1.5 MB/s eta 0:00:01
   ------------------------- -------------- 1.8/2.9 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 1.9 MB/s  0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.13

In [3]:
import psycopg2

print("psycopg2 is working!")

psycopg2 is working!

In [4]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="gtd_db",
    user="postgres",
    password="password"
)

print("PostgreSQL connected successfully!")

PostgreSQL connected successfully!

In [5]:
with open(
    r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\globalterrorismdb_0718dist.csv",
    "r",
    encoding="latin1"
) as f:
    cur = conn.cursor()

    cur.copy_expert(
        """
        COPY raw_gtd_events
        FROM STDIN
        WITH (
            FORMAT CSV,
            HEADER TRUE,
            DELIMITER ',',
            QUOTE '"',
            ESCAPE '"'
        )
        """,
        f
    )

    conn.commit()
    cur.close()

print("CSV imported successfully!")

BadCopyFileFormat: missing data for column "nkill"
CONTEXT:  COPY raw_gtd_events, line 171057: "201701100015,2017,1,10,,0,,4,Afghanistan,6,South Asia,Farah,Kanisk,32.532429,62.325817,1,0,,"01/10/2..."

In [6]:
import csv

csv_path = r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\globalterrorismdb_0718dist.csv"

with open(csv_path, "r", encoding="latin1", newline="") as f:
    reader = csv.reader(f)
    
    rows = list(reader)

print("Header columns:", len(rows[0]))
print("Last row columns:", len(rows[-1]))
print("Last row:", rows[-1])

Header columns: 135
Last row columns: 98
Last row: ['201701100015', '2017', '1', '10', '', '0', '', '4', 'Afghanistan', '6', 'South Asia', 'Farah', 'Kanisk', '32.532429', '62.325817', '1', '0', '', '01/10/2017: A roadside bomb detonated targeting a civilian vehicle in Kanisk, Farah, Afghanistan. Two civilians were killed in the blast. No group claimed responsibility for the attack.', '1', '1', '1', '0', '', '', '0', '1', '0', '3', 'Bombing/Explosion', '', '', '', '', '14', 'Private Citizens & Property', '73', 'Vehicles/Transportation', 'Not Applicable', 'Vehicle', '4', 'Afghanistan', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Unknown', '', '', '', '', '', '', '0', '', '', '0', '-99', '0', '0', '', '', '', '', '', '', '', '', '', '6', 'Explosives', '16', 'Unknown Explosive Type', '', '', '', '', '', '', '', '', '', '', '', '', 'A road']

In [7]:
import csv

csv_path = r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\globalterrorismdb_0718dist.csv"

with open(csv_path, "r", encoding="latin1", newline="") as f:
    reader = csv.reader(f)

    header = next(reader)

    for line_number, row in enumerate(reader, start=2):
        if len(row) != len(header):
            print("Problem found!")
            print("CSV line:", line_number)
            print("Columns found:", len(row))
            print("Expected:", len(header))
            print("Event ID:", row[0])

Problem found!
CSV line: 171057
Columns found: 98
Expected: 135
Event ID: 201701100015

In [8]:
import csv

input_file = r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\globalterrorismdb_0718dist.csv"
output_file = r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\gtd_import_ready.csv"

with open(input_file, "r", encoding="latin1", newline="") as infile, \
     open(output_file, "w", encoding="latin1", newline="") as outfile:

    reader = csv.reader(infile)
    writer = csv.writer(outfile)

    header = next(reader)
    writer.writerow(header)

    skipped = 0
    imported_rows = 0

    for row in reader:
        if len(row) != len(header):
            skipped += 1
            continue

        writer.writerow(row)
        imported_rows += 1

print("Import-ready CSV created!")
print("Valid rows:", imported_rows)
print("Skipped rows:", skipped)

Import-ready CSV created!
Valid rows: 171055
Skipped rows: 1

In [9]:
with open(
    r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\gtd_import_ready.csv",
    "r",
    encoding="latin1"
) as f:

    cur = conn.cursor()

    cur.copy_expert(
        """
        COPY raw_gtd_events
        FROM STDIN
        WITH (
            FORMAT CSV,
            HEADER TRUE,
            DELIMITER ',',
            QUOTE '"',
            ESCAPE '"'
        )
        """,
        f
    )

    conn.commit()
    cur.close()

print("CSV imported successfully!")

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

In [10]:
conn.rollback()
print("Transaction reset successfully!")

Transaction reset successfully!

In [11]:
with open(
    r"C:\Users\MY PC\Desktop\Global-Terrorism-Analysis\data\gtd_import_ready.csv",
    "r",
    encoding="latin1"
) as f:

    cur = conn.cursor()

    cur.copy_expert(
        """
        COPY raw_gtd_events
        FROM STDIN
        WITH (
            FORMAT CSV,
            HEADER TRUE,
            DELIMITER ',',
            QUOTE '"',
            ESCAPE '"'
        )
        """,
        f
    )

    conn.commit()
    cur.close()

print("CSV imported successfully!")

CSV imported successfully!